- name: Configure Redis 
  hosts: redis 
  become: yes
  tasks:
   - name: Disable redis default version 
     ansible.builtin.command: dnf module disable redis -y
   
   - name: Enable redis 7 version
     ansible.builtin.command: dnf module enable redis:7 -y
   
   - name: Install redis 
     ansible.builtin.dnf:
      name: redis
      state: present 
   
   - name: Allow remote connection
     ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
   
   - name: change protected mode from yes to no 
     ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

   - name: Start and Enable redis service 
     ansible.builtin.service:
      name: redis
      state: started
      enabled: yes