$ANSIBLE_VAULT;1.1;AES256
63633964316564306562323766333838353562353339303564346530653264623130663966643764
6533333335313765643761336432663466373638623562330a326462636562653531306263313730
32323034353530383665326539303963363233376564316463653261376564306435346231653063
3263613964303831300a383436643236616139393932306631663731356335653261356465303137
35323261666333656436623230653165653135383261626561326435623861633636343333663538
6231393237343132646137666332393533353161363065633264