$ANSIBLE_VAULT;1.1;AES256
37343336623733316333626563363436363066383037643832353833646330656637383266333234
3963633764343537373330343333396461363335363434390a663061353466356230396335363763
36303037393735363039356431376436366666333032393965636538393733346436326461346533
6532653138636264640a666532626166356331643433333136636161653736333161323438346430
62326665386232333930353065326261633538323230373337356139343166393730613032373839
3663353539636362393031366563326531643366366564306537