- name: Setup python
  ansible.builtin.import_role:
   name: common
   tasks_from: python-setup.yaml

- name: Setup app
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: 