- name: Disable nginx default version 
  ansible.builtin.command: dnf module disable nginx -y

- name: Enable nginx:1.24 version 
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Install nginx 
  ansible.builtin.dnf:
   name: nginx 
   state: present

- name: Start and Enable the service 
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes

- name: Remove the folder
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent

- name: Create html folder
  ansible.builtin.file:
   name: /usr/share/nginx/html
   state: directory

- name: Download the frontend code
  ansible.builtin.get_url:
  url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
  dest: /tmp/frontend.zip

- name: Unarchive frontend code
  ansible.builtin.unarchive:
   src: /tmp/frontend.zip
   dest: /usr/share/nginx/html
   remote_src: yes

- name: Remove default nginx 
  ansible.builtin.file:
   name: /etc/nginx/nginx.conf
   state: absent

- name: Copy nginx.conf file
  ansible.builtin.template:
   src: nginx.conf.j2
   dest: /etc/nginx/nginx.conf
  notify: Restart nginx service