- name: Copy rabbitmq repo
  ansible.builtin.copy:
   src: rabbitmq.repo
   dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq package
  ansible.builtin.dnf:
   name: rabbitmq-server
   state: present

- name: Start and Enable service
  ansible.builtin.service:
   name: rabbitmq-server
   state: started
   enabled: yes

- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
   user: roboshop 
   password: roboshop123
   permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present