- name: Install mysql package
  ansible.builtin.dnf: 
   name: mysql-server
   state: present

- name: Start and enable service
  ansible.builtin.service:
   name: mysqld
   state: started
   enabled: yes

- name: set up root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{MYSQL_ROOT_PASSWORD}}"
