- name: Setting up the nodejs 
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs-setup.yaml

- name: Setting up the app
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: Starting the service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup.yaml

- name: Copy mongo.repo
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client package
  ansible.builtin.dnf:
   name: mongodb-mongosh
   state: present

- name: check the products are available or not 
  ansible.builtin.command: mongosh --host "{{MONGODB_HOST}}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: Display the output in JSON format
  ansible.builtin.debug:
   msg: "{{catalogue_output}}"

- name: Load the mongodb products
  ansible.builtin.shell: mongosh --host "{{MONGODB_HOST}}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: Retsrat the {{component}} service
  ansible.builtin.service:
   name: "{{component}}"
   state: restarted