- name: message-1
  ansible.builtin.debug:
   msg: "Hi from MSG-1"

- name: message-2
  ansible.builtin.debug:
   msg: "Hi from MSG-2"

- name: set_fact
  ansible.builtin.set_fact:
    os: "Debian"

- name: message-3
  ansible.builtin.debug:
   msg: "Hi from MSG-3"