# - name: Disable nodejs default version
#   ansible.builtin.command: dnf module disable nodejs -y 

- name: Enable nodejs 20 version 
  ansible.builtin.shell: dnf module enable nodejs -y 

- name: Install nodejs 
  ansible.builtin.dnf:
   name: nodejs
   state: present
   update_cache: yes

