- name: copy {{ component }} service
  ansible.builtin.copy:
   src: "{{ component }}.service.j2"
   dest: "/etc/systemd/system/{{ component }}.service"

- name: Reload the daemon
  ansible.builtin.systemd:
   daemon_reload: yes