- name: Setting up the nodejs 
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs-setup.yaml

- name: Setting up the application
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: Settin up the service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup.yaml